SHOW TABLES;
CREATE TABLE IF NOT EXISTS user(
    id INT PRIMARY KEY,
    username VARCHAR(50) UNIQUE,
    email VARCHAR(30) UNIQUE NOT NULL,
    password VARCHAR(50) NOT NULL
);
ALTER TABLE user MODIFY email VARCHAR(255);
